[workspace-to-monitor-force-assignment]
# Keep the secondary monitor for low-priority workspaces only.
4 = 'secondary'
5 = 'secondary'
6 = 'secondary'
7 = 'secondary'
8 = 'secondary'
9 = 'secondary'
F = 'secondary'
U = 'secondary'
