# https://draculatheme.com/kitty
#
# Installation instructions:
#
#  cp dracula.conf ~/.config/kitty/
#  echo "include dracula.conf" >> ~/.config/kitty/kitty.conf
#
# Then reload kitty for the config to take affect.
# Alternatively copy paste below directly into kitty.conf

foreground            #f8f8f2
background            #061627

selection_foreground  #ffffff
selection_background  #44475a

url_color #8be9fd

# black 
color0  #1a3a5e
color8  #63676c

# red
color1  #ea4d44
color9  #eb60ad

# green
color2  #88fbd2
color10 #99fbda

# yellow
color3  #fcf392
color11 #faf4b5

# blue
color4  #3674f0
color12 #4f8bf6

# magenta
color5  #be94e4
color13 #a782f7

# cyan
color6  #ec69cf
color14 #ed73d2

# white
color7  #75f9a9
color15 #8df8c2

# Cursor colors
cursor            #7efba5
cursor_text_color background

# Tab bar colors
active_tab_foreground   #282a36
active_tab_background   #f8f8f2
inactive_tab_foreground #282a36
inactive_tab_background #6272a4
# Marks
mark1_foreground #282a36
mark1_background #ff5555

# Splits/Windows
active_border_color #f8f8f2
inactive_border_color #6272a4
