# ==========================
# Ubuntu 内层 Tmux 极简配置
# ==========================

# 1. 保持默认 Prefix 为 C-b (完美穿透 Mac 的 C-a)
set -g prefix C-b

# 2. 鼠标与 Vim 模式 (继承你的习惯)
set -g mouse on
set-window-option -g mode-keys vi

# 3.UI-bar设计（三种模式切换）
# 顶部状态栏
set -g status on
set -g status-position top
set -g status-justify left
set -g status-interval 1

# 整体背景压低存在感
set -g status-style "bg=#1a1b26,fg=#a9b1d6"

# 不要右侧内容
set -g status-right ""

# 模式变量
set -g @attack 0
set -g @mode_name "Ubuntu"
set -g @mode_bg "#7aa2f7"
set -g @mode_fg "#1a1b26"

# 手动切换 Attack
# Prefix + a
bind-key a if -F '#{==:#{@attack},1}' \
  'set -gq @attack 0 \; run-shell "~/.config/tmux/mode.sh" \; display-message "Attack OFF"' \
  'set -gq @attack 1 \; run-shell "~/.config/tmux/mode.sh" \; display-message "Attack ON"'
# 重载配置
# Prefix + r
bind-key r source-file ~/.config/tmux/tmux.conf \; run-shell "~/.config/tmux/update_mode.sh" \; display-message "tmux config reloaded"

# 每次刷新状态栏时顺手更新 mode
# 注意：脚本本身不输出内容，只更新 tmux 变量
set -g status-left '#(~/.config/tmux/update_mode.sh >/dev/null 2>&1)#[fg=#{@mode_fg},bg=#{@mode_bg},bold] #{@mode_name} #[default] '

set -g status-left-length 20

# window 区域弱化
set -g window-status-separator ""
set -g window-status-format " #[fg=#565f89]#W#[default] "
set -g window-status-current-format "#[fg=#c0caf5,bold] #W #[default]"


# 4. 兼容你的分屏习惯 (可选)
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind-key -n C-h select-pane -L
bind-key -n C-j select-pane -D
bind-key -n C-k select-pane -U
bind-key -n C-l select-pane -R
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
# （可选）如果你习惯用 Ctrl+l 来清屏，绑定了切换窗格后清屏键会被覆盖。
# 加上下面这行，你可以通过输入 Prefix (Ctrl+b) + Ctrl+l 来强制清屏
# 1. 开启 vi 风格的快捷键（必须开启，否则后面的 -T copy-mode-vi 不生效）
set-window-option -g mode-keys vi

# 2. 【核心修复】阻止鼠标拖拽松开后自动退出复制模式
unbind -T copy-mode-vi MouseDragEnd1Pane

# 3. 绑定 'y' 键执行复制，并退出复制模式
bind-key -T copy-mode-vi 'y' send-keys -X copy-selection-and-cancel

# ==========================================
# 终极 OSC 52 物理穿透：拦截 y 键，强行发送魔法指令
# ==========================================
# 我们利用 copy-pipe-and-cancel 把选中的文本通过管道传给后面的 shell 命令。
# base64 编码后，拼装成你刚刚测试成功的 OSC52 协议，然后直接砸向当前终端的物理设备文件 (#{pane_tty})！
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "base64 | tr -d '\n' | awk '{printf \"\\033]52;c;%s\\a\", \$0}' > #{pane_tty}"
